//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageView.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageView.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program depends on other work (libraries or art files). Please check out About/License for a complete information..
        /// </summary>
        internal static string AboutDependencies {
            get {
                return ResourceManager.GetString("AboutDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free and open source software..
        /// </summary>
        internal static string AboutFreeAndOpenSource {
            get {
                return ResourceManager.GetString("AboutFreeAndOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Latest Version:.
        /// </summary>
        internal static string AboutGetLatest {
            get {
                return ResourceManager.GetString("AboutGetLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under the MIT License. Copyright © 2020, Tony Pottier.
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to support this program, please consider donating using the donate button below:.
        /// </summary>
        internal static string AboutPleaseDonate {
            get {
                return ResourceManager.GetString("AboutPleaseDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every donation is greatly appreciated!.
        /// </summary>
        internal static string AboutPleaseDonate2 {
            get {
                return ResourceManager.GetString("AboutPleaseDonate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code Repository:.
        /// </summary>
        internal static string AboutSourceCodeRepo {
            get {
                return ResourceManager.GetString("AboutSourceCodeRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.{1}.{2}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Fit.
        /// </summary>
        internal static string BestFit {
            get {
                return ResourceManager.GetString("BestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        internal static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to Height.
        /// </summary>
        internal static string FitToHeight {
            get {
                return ResourceManager.GetString("FitToHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to Width.
        /// </summary>
        internal static string FitToWidth {
            get {
                return ResourceManager.GetString("FitToWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Flip.
        /// </summary>
        internal static string HorizontalFlip {
            get {
                return ResourceManager.GetString("HorizontalFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as last viewed image.
        /// </summary>
        internal static string ImageModeRestore {
            get {
                return ResourceManager.GetString("ImageModeRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition, this software depends on additional libraries and art files; under the following licenses:.
        /// </summary>
        internal static string LicenseAdditional {
            get {
                return ResourceManager.GetString("LicenseAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error while loading the license files.
        ///Please refer to https://getimageview.net.
        /// </summary>
        internal static string LicenseErrorMessage {
            get {
                return ResourceManager.GetString("LicenseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading license files.
        /// </summary>
        internal static string LicenseErrorTitle {
            get {
                return ResourceManager.GetString("LicenseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is licensed under the following license:.
        /// </summary>
        internal static string LicenseMain {
            get {
                return ResourceManager.GetString("LicenseMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Image.
        /// </summary>
        internal static string NextImage {
            get {
                return ResourceManager.GetString("NextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image File.
        /// </summary>
        internal static string OpenImageFile {
            get {
                return ResourceManager.GetString("OpenImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Image Size Mode.
        /// </summary>
        internal static string PickImageSizeMode {
            get {
                return ResourceManager.GetString("PickImageSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Image.
        /// </summary>
        internal static string PreviousImage {
            get {
                return ResourceManager.GetString("PreviousImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Mode.
        /// </summary>
        internal static string ReaderMode {
            get {
                return ResourceManager.GetString("ReaderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Size.
        /// </summary>
        internal static string RealSize {
            get {
                return ResourceManager.GetString("RealSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Left (Counter Clockwise).
        /// </summary>
        internal static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Right (Clockwise).
        /// </summary>
        internal static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image Copy As....
        /// </summary>
        internal static string SaveImageCopyAs {
            get {
                return ResourceManager.GetString("SaveImageCopyAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically rotate.
        /// </summary>
        internal static string SettingsAutoRotate {
            get {
                return ResourceManager.GetString("SettingsAutoRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically rotate the image according to its orientation metadata.
        /// </summary>
        internal static string SettingsAutoRotateExplanation {
            get {
                return ResourceManager.GetString("SettingsAutoRotateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Default Apps.
        /// </summary>
        internal static string SettingsChooseDefaultApps {
            get {
                return ResourceManager.GetString("SettingsChooseDefaultApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Application.
        /// </summary>
        internal static string SettingsDefaultApp {
            get {
                return ResourceManager.GetString("SettingsDefaultApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the button below to launch Windows Default Applications. From there, you can select ImageView to be your default Photo Viewer.
        ///If you are using the portable version of ImageView, you need to run it with administrator privilege for this functionality to work..
        /// </summary>
        internal static string SettingsDefaultAppExplanation {
            get {
                return ResourceManager.GetString("SettingsDefaultAppExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Image Size Mode.
        /// </summary>
        internal static string SettingsDefaultSizeMode {
            get {
                return ResourceManager.GetString("SettingsDefaultSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When loading an image, set image size mode to:.
        /// </summary>
        internal static string SettingsDefaultSizeModeExplanation {
            get {
                return ResourceManager.GetString("SettingsDefaultSizeModeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string SettingsHistory {
            get {
                return ResourceManager.GetString("SettingsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value of 0 will disable history. The maximum value is 99..
        /// </summary>
        internal static string SettingsHistoryExplanation {
            get {
                return ResourceManager.GetString("SettingsHistoryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items to keep in history:.
        /// </summary>
        internal static string SettingsHistoryMaxSize {
            get {
                return ResourceManager.GetString("SettingsHistoryMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save History When Exiting Program.
        /// </summary>
        internal static string SettingsHistorySaveOnExit {
            get {
                return ResourceManager.GetString("SettingsHistorySaveOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Viewing.
        /// </summary>
        internal static string SettingsImageViewing {
            get {
                return ResourceManager.GetString("SettingsImageViewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to display each image:.
        /// </summary>
        internal static string SettingsSlideshowTimer {
            get {
                return ResourceManager.GetString("SettingsSlideshowTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        internal static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears the first time you start ImageView.
        ///Please select your language.
        ///You can always change it later by going into the application settings..
        /// </summary>
        internal static string SplashExplanation {
            get {
                return ResourceManager.GetString("SplashExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Language: {0}.
        /// </summary>
        internal static string SplashSelected {
            get {
                return ResourceManager.GetString("SplashSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string SplashTitle {
            get {
                return ResourceManager.GetString("SplashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Flip.
        /// </summary>
        internal static string VerticalFlip {
            get {
                return ResourceManager.GetString("VerticalFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! Open an image file to begin browsing..
        /// </summary>
        internal static string WelcomeStatus {
            get {
                return ResourceManager.GetString("WelcomeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Tool.
        /// </summary>
        internal static string ZoomTool {
            get {
                return ResourceManager.GetString("ZoomTool", resourceCulture);
            }
        }
    }
}
